# Generated by Django 2.2.9 on 2020-10-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='discription',
            new_name='description',
        ),
    ]
